Feat/improve response
catalyzt-tech/Worker pull request #3
Opened 2024-08-28 12:35 UTC by wit03

# Description

[//]: # "Please include a summary of the changes and the related issue. (You can write below without deleting this comment)"
This pull request introduced changes in run script, added important field to general API response, and add more data to scraping script.

### What
[//]: # "Briefly describe this feature / fix / refactor (You can write below without deleting this comment)"
- Refactor `run script` by removing unused script.
- Add `fs.stats.mtime` to the base api response so client can get mTime for each file (mTime = modified time.)
- feat: projectUid to RetroPGF 5 Scrape.

### Why
[//]: # "Describe the reason why we need this feature / fix / refactor or refer to Jira Ticket (You can write below without deleting this comment)"
- Added modified time to API response can ensure us about the health of our CRON job and also this data can be utilize 

## Type of change

Please check the relevent option with `x`.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if needed)
- [x] My changes generate no new warnings
- [x] I have tested on my `Local Machine`

2024-08-28 12:46 UTC, wit03 commented on data/retropgf5-live-data/retropgf5-live-data.json
> +        "projectUid": "0x985a1ed485458d7c383c8b59a18856183197783883014c74b865468769436c52"
These are data from user which we didn't involve in writing process, we can skip this.

2024-08-28 12:46 UTC, wit03 commented on data/retropgf5-live-data/retropgf5-live-data.json
> +        "projectUid": "0x6ee546715053790bda72f913925b782461830ccdcc14ad12a2f288641510f448"
These are data from user which we didn't involve in writing process, we can skip this.

2024-08-28 12:47 UTC, wit03 commented on data/retropgf5-live-data/retropgf5-live-data.json
> +        "projectUid": "0x1480383a90f1ab95cfedee6ea130dca700e5236eceb7dcf3f08a0e96b43c90aa"
https://github.com/mali030303/Dragons-On-Op-Stack--

2024-08-28 14:04 UTC, Billy19191 requested changes
Other thing look goods, only few comment here

2024-08-28 14:04 UTC, Billy19191 commented on src/scripts/retropgf5-live-data/retropgf5-live-data.ts
> +                    const response = await axios.get(url.metadataURL);
Please add type for response for this `axios.get(url.metadataURL)` (maybe change schema or model in the future)

2024-08-28 14:04 UTC, Billy19191 commented on src/scripts/retropgf5-live-data/retropgf5-live-data.ts
> +            const responses: any[] = [];
Add responses type (please avoid any type)

2024-08-28 14:14 UTC, wit03 commented
@Billy19191 I don't think it's worth wasting time here, since the scraping script will not be used for long (only one month) and also they are not the codebase (unlike RetroPGFHub, and core functionality of Worker in other folders)

Another reason apart from that is we don't have End-2-End typesafe anyway, so by adding type to this wouldn't affect the type on Frontend.

We should better focus on the Worker codebase in other folders apart from /scripts 

@TGRZiminiar Do you have any opinion?

2024-08-28 14:58 UTC, Billy19191 commented
As I understand, this script is temporary, right? At first, I thought that this gonna be permanent in the Worker codebase. So, in this case, you can you with your solution with any type.

2024-08-28 15:43 UTC, Billy19191 approved these changes

2024-08-29 15:58 UTC, TGRZiminiar approved these changes
Approved

2024-08-29 15:58 UTC, merged